export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const FILTER_ARTISTS = 'FILTER_ARTISTS';
export const GET_ALL_ARTISTS = 'GET_ALL_ARTISTS';
