/*eslint-disable*/

//PRODUCTS 
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';

//ARTIST
export const FILTER_ARTISTS = 'FILTER_ARTISTS';
export const SEARCH_BY_ARTIST = 'SEARCH_BY_ARTIST';

//CATEGORIES
export const NEW_CATEGORY = 'NEW_CATEGORY';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

//AUTHORS
export const NEW_AUTHOR = 'NEW_AUTHOR';
export const GET_ALL_AUTHORS = 'GET_ALL_AUTHORS';

//SERIES
export const GET_ALL_SERIES = 'GET_ALL_SERIES';

//LOADING
export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

//FILTERS
export const FILAZZA = 'FILAZZA'

//SHOPPING-CART
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';